#!/bin/sh

# Orange Pi Zero 3 single-port bypass-router mode.
# eth0 obtains its address from the main router through DHCP.

[ -e /etc/config/network ] || touch /etc/config/network

uci -q set network.lan='interface'
uci -q set network.lan.device='eth0'
uci -q set network.lan.proto='dhcp'

uci -q delete network.lan.ipaddr
uci -q delete network.lan.netmask
uci -q delete network.lan.gateway
uci -q delete network.lan.dns
uci -q delete network.lan.ip6assign

uci commit network

# Do not provide DHCP/RA service to the upstream LAN.
uci -q set dhcp.lan='dhcp'
uci -q set dhcp.lan.interface='lan'
uci -q set dhcp.lan.ignore='1'
uci -q set dhcp.lan.dhcpv4='disabled'
uci -q set dhcp.lan.dhcpv6='disabled'
uci -q set dhcp.lan.ra='disabled'
uci -q set dhcp.lan.ndp='disabled'

uci commit dhcp

uci -q set system.@system[0].hostname='OrangePi-Zero3'
uci commit system

exit 0
